# Generated by Django 4.0.4 on 2022-04-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_alter_idea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
