# Generated by Django 4.0.4 on 2022-05-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='idea.category'),
        ),
    ]
