# Generated by Django 4.0.4 on 2022-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_remove_idea_category_idea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
