# Generated by Django 4.0.4 on 2022-05-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_name'),
        ('idea', '0003_remove_idea_category_idea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
