# Generated by Django 4.0.4 on 2022-06-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_requester_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_idea', models.TextField()),
                ('user', models.CharField(max_length=150)),
                ('base_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
            ],
        ),
    ]
